name: Watchdog

on:
  workflow_run:
    workflows: ["Weather Bots"]
    types:
      - completed

jobs:
  restart_weather_bots:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Trigger Watchdog Workflow
        uses: peter-evans/workflow-dispatch@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: Arval-o/Discord-Weather-Fan   
          workflow: spc.yml                    
          ref: main                               
